export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'

export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST'
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS'
export const CURRENT_USER_FAILURE = 'CURRENT_USER_FAILURE'

export const ENTRIES_REQUEST = 'ENTRIES_REQUEST'
export const ENTRIES_REQUEST_SUCCESS = 'ENTRIES_REQUEST_SUCCESS'
export const ENTRIES_REQUEST_FAILURE = 'ENTRIES_REQUEST_FAILURE'
